// AudioReactive.js — resizable UI for band-followed audio event extraction.
autowatch=1; inlets=1; outlets=1;
mgraphics.init(); mgraphics.relative_coords=0; mgraphics.autofill=0;
var C={base:[.055,.055,.059,1],surface:[.086,.086,.094,1],surf2:[.126,.126,.141,1],hair:[.173,.173,.192,1],text:[.926,.926,.926,1],dim:[.541,.541,.561,1],faint:[.361,.361,.380,1],accent:[.722,1,.361,1]};
var FONT="Helvetica Neue",W=494,H=323,P=8,N=180,head=0,levels=[],envs=[],flash=0,regions=[],drag=-1;
var V={low:80,high:8000,order:2,attack:10,release:250,drive:4,threshold:.5,hysteresis:.05,holdoff:100};
var Vlen=400;
for(var i=0;i<N;i++){levels.push(0);envs.push(0);}
function clamp(v,a,b){return v<a?a:(v>b?b:v);} function setc(c){mgraphics.set_source_rgba(c[0],c[1],c[2],c[3]);}
function rect(x,y,w,h,c){setc(c);mgraphics.rectangle(x,y,w,h);mgraphics.fill();} function line(x1,y1,x2,y2,c,lw){setc(c);mgraphics.set_line_width(lw||1);mgraphics.move_to(x1,y1);mgraphics.line_to(x2,y2);mgraphics.stroke();}
function font(s){mgraphics.select_font_face(FONT);mgraphics.set_font_size(s);} function meas(s,z){font(z);var m=mgraphics.text_measure(""+s);return m&&m.length?m[0]:0;}
function text(x,y,s,c,z,right){setc(c);font(z);if(right)x-=meas(s,z);mgraphics.move_to(x,y);mgraphics.show_text(""+s);} function trk(s){return(""+s).toUpperCase().split("").join(" ");} function alpha(c,a){return[c[0],c[1],c[2],a];}
function onresize(w,h){W=w;H=h;mgraphics.redraw();} function level(v){levels[head]=clamp(v,0,1);} function env(v){envs[head]=clamp(v,0,1);head=(head+1)%N;mgraphics.redraw();}
function event(){flash=1;mgraphics.redraw();var t=new Task(function(){flash=0;mgraphics.redraw();},this);t.schedule(90);}
function low(v){V.low=clamp(v,20,20000);mgraphics.redraw();} function high(v){V.high=clamp(v,20,20000);mgraphics.redraw();} function order(v){V.order=clamp(Math.round(v),1,8);mgraphics.redraw();}
function attack(v){V.attack=v;mgraphics.redraw();} function release(v){V.release=v;mgraphics.redraw();} function drive(v){V.drive=v;mgraphics.redraw();} function threshold(v){V.threshold=v;mgraphics.redraw();}
function hysteresis(v){V.hysteresis=v;mgraphics.redraw();} function holdoff(v){V.holdoff=v;mgraphics.redraw();} function length(v){Vlen=v;mgraphics.redraw();}
function paint(){P=clamp(Math.round(W*.02),6,12);regions=[];rect(0,0,W,H,C.base);text(P,16,trk("audio reactive"),C.dim,9,false);text(W-P,16,flash?"EVENT":"LISTENING",flash?C.accent:C.faint,8,true);var sy=24,sh=Math.max(54,Math.min(92,H*.28));drawScope(P,sy,W-P*2,sh);var fy=sy+sh+7;drawBand(P,fy,W-P*2,28);var cy=fy+35,ch=H-cy-P;drawControls(P,cy,W-P*2,ch);}
function drawScope(x,y,w,h){rect(x,y,w,h,C.surface);line(x,y+h*(1-V.threshold),x+w,y+h*(1-V.threshold),alpha(C.accent,.35),1);setc(alpha(C.dim,.45));mgraphics.set_line_width(1);mgraphics.move_to(x,y+h);for(var k=1;k<N;k++)mgraphics.line_to(x+w*k/(N-1),y+h*(1-levels[(head+k)%N]));mgraphics.stroke();setc(alpha(C.accent,.9));mgraphics.set_line_width(1.4);mgraphics.move_to(x,y+h);for(var j=1;j<N;j++)mgraphics.line_to(x+w*j/(N-1),y+h*(1-envs[(head+j)%N]));mgraphics.stroke();}
function logNorm(v,a,b){return Math.log(v/a)/Math.log(b/a);} function logValue(t,a,b){return a*Math.pow(b/a,clamp(t,0,1));}
function drawBand(x,y,w,h){text(x,y+8,trk("band"),C.faint,7,false);var x0=x+52,x1=x+w-63,rw=x1-x0,lo=x0+rw*logNorm(V.low,20,20000),hi=x0+rw*logNorm(V.high,20,20000);line(x0,y+15,x1,y+15,C.hair,5);line(lo,y+15,hi,y+15,alpha(C.accent,.45),5);rect(lo-2,y+9,5,13,C.accent);rect(hi-2,y+9,5,13,C.accent);text(x0,y+28,fmtHz(V.low),C.dim,7,false);text(x1,y+28,fmtHz(V.high),C.dim,7,true);text(x+w,y+18,"ORDER "+V.order,C.accent,8,true);regions.push({n:"low",x:x0-8,y:y,w:rw+16,h:h});regions.push({n:"order",x:x+w-58,y:y,w:58,h:24});}
function fmtHz(v){return v>=1000?(v/1000).toFixed(v<10000?1:0)+"k":Math.round(v)+"Hz";}
function drawControls(x,y,w,h){var gap=8,left=w*.61,right=w-left-gap,cw=(left-gap)/2,row=Math.max(25,h/3),items=[["attack","ATTACK",V.attack,.5,500,"ms",1],["release","RELEASE",V.release,10,3000,"ms",1],["drive","DRIVE",V.drive,.25,32,"×",1],["threshold","THRESHOLD",V.threshold,.01,.99,"",0],["hysteresis","HYSTERESIS",V.hysteresis,0,.3,"",0],["holdoff","HOLDOFF",V.holdoff,0,1000,"ms",0]];for(var i=0;i<6;i++){var col=i%2,r=Math.floor(i/2),xx=x+col*(cw+gap),yy=y+r*row;control(xx,yy,cw,row-5,items[i]);}drawEnvelopeSlot(x+left+gap,y,right,h);}
function drawEnvelopeSlot(x,y,w,h){rect(x,y,w,h,C.surface);text(x+6,y+11,trk("envelope"),C.faint,7,false);text(x+w-6,y+11,"BREAKPOINT / CURVE",C.dim,7,true);text(x+6,y+h-5,trk("length"),C.faint,7,false);text(x+w-6,y+h-5,Math.round(Vlen)+" MS",C.text,8,true);}
function control(x,y,w,h,it){var n=it[0],label=it[1],v=it[2],a=it[3],b=it[4],unit=it[5],lg=it[6],t=lg?logNorm(Math.max(v,a),a,b):(v-a)/(b-a);rect(x,y,w,h,C.surface);text(x+5,y+10,label,C.faint,7,false);var shown=(unit===""?v.toFixed(2):(unit==="×"?v.toFixed(1)+unit:Math.round(v)+unit));text(x+w-5,y+10,shown,C.text,8,true);rect(x+5,y+h-7,w-10,3,C.surf2);rect(x+5,y+h-7,(w-10)*clamp(t,0,1),3,alpha(C.accent,.55));regions.push({n:n,x:x,y:y,w:w,h:h,a:a,b:b,lg:lg});}
function setRegion(r,x){if(r.n==="order")return;var t=clamp((x-r.x)/r.w,0,1),v=r.lg?logValue(t,r.a,r.b):r.a+t*(r.b-r.a);V[r.n]=v;outlet(0,r.n,v);mgraphics.redraw();}
function onclick(x,y){for(var i=regions.length-1;i>=0;i--){var r=regions[i];if(x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h){if(r.n==="order"){V.order=V.order%8+1;outlet(0,"order",V.order);mgraphics.redraw();return;}if(r.n==="low"){var x0=r.x+8,rw=r.w-16,t=clamp((x-x0)/rw,0,1),hz=logValue(t,20,20000);drag=Math.abs(Math.log(hz/V.low))<Math.abs(Math.log(hz/V.high))?"low":"high";V[drag]=drag==="low"?Math.min(hz,V.high/1.05):Math.max(hz,V.low*1.05);outlet(0,drag,V[drag]);mgraphics.redraw();return;}drag=i;setRegion(r,x);return;}}}
function ondrag(x,y,but){if(but===0){drag=-1;return;}if(drag==="low"||drag==="high"){var r=regions[0],t=clamp((x-(r.x+8))/(r.w-16),0,1),hz=logValue(t,20,20000);V[drag]=drag==="low"?Math.min(hz,V.high/1.05):Math.max(hz,V.low*1.05);outlet(0,drag,V[drag]);mgraphics.redraw();return;}if(drag>=0)setRegion(regions[drag],x);} onclick.local=1;ondrag.local=1;
