{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 9, "minor": 0, "revision": 0, "architecture": "x64", "modernui": 1 },
    "rect": [ 100.0, 100.0, 760.0, 600.0 ],
    "openinpresentation": 1,
    "boxes": [
      { "box": { "id": "in-a", "maxclass": "inlet", "numinlets": 0, "numoutlets": 1, "patching_rect": [ 40.0, 35.0, 30.0, 30.0 ] } },
      { "box": { "id": "in-b", "maxclass": "inlet", "numinlets": 0, "numoutlets": 1, "patching_rect": [ 150.0, 35.0, 30.0, 30.0 ] } },
      { "box": { "id": "in-op", "maxclass": "inlet", "numinlets": 0, "numoutlets": 1, "patching_rect": [ 300.0, 35.0, 30.0, 30.0 ] } },
      { "box": { "id": "dir-a", "maxclass": "newobj", "text": "gen~ signChangeGates", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 40.0, 100.0, 137.0, 22.0 ] } },
      { "box": { "id": "dir-b", "maxclass": "newobj", "text": "gen~ signChangeGates", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 190.0, 100.0, 137.0, 22.0 ] } },
      { "box": { "id": "morph", "maxclass": "newobj", "text": "gen~ morphCombineGates", "numinlets": 2, "numoutlets": 1, "patching_rect": [ 105.0, 210.0, 159.0, 22.0 ] } },
      { "box": { "id": "gate", "maxclass": "newobj", "text": "gen~ motionLogicGate", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 105.0, 270.0, 137.0, 22.0 ] } },
      { "box": { "id": "edge", "maxclass": "newobj", "text": "edge~", "numinlets": 1, "numoutlets": 2, "patching_rect": [ 105.0, 330.0, 42.0, 22.0 ] } },
      { "box": { "id": "rise", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 75.0, 400.0, 30.0, 30.0 ] } },
      { "box": { "id": "fall", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 170.0, 400.0, 30.0, 30.0 ] } },
      { "box": { "id": "scale", "maxclass": "newobj", "text": "scale -1. 1. 0. 5.", "numinlets": 6, "numoutlets": 1, "patching_rect": [ 300.0, 90.0, 94.0, 22.0 ] } },
      { "box": { "id": "op", "maxclass": "flonum", "varname": "combineSelect", "numinlets": 1, "numoutlets": 2, "patching_rect": [ 420.0, 90.0, 55.0, 22.0 ] } },
      { "box": { "id": "op-gen", "maxclass": "newobj", "text": "prepend op", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 420.0, 130.0, 69.0, 22.0 ] } },
      { "box": { "id": "op-ui", "maxclass": "newobj", "text": "prepend op", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 500.0, 130.0, 69.0, 22.0 ] } },
      { "box": { "id": "ui", "maxclass": "v8ui", "filename": "MotionLogic.js", "textfile": { "filename": "MotionLogic.js", "flags": 0, "embed": 0, "autowatch": 1 }, "varname": "ui", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "parameter_enable": 0, "border": 0, "patching_rect": [ 500.0, 200.0, 184.0, 95.0 ], "presentation": 1, "presentation_rect": [ 0.0, 0.0, 300.0, 204.0 ] } },
      { "box": { "id": "snap-a", "maxclass": "newobj", "text": "snapshot~ 20", "numinlets": 2, "numoutlets": 1, "patching_rect": [ 40.0, 145.0, 81.0, 22.0 ] } },
      { "box": { "id": "snap-b", "maxclass": "newobj", "text": "snapshot~ 20", "numinlets": 2, "numoutlets": 1, "patching_rect": [ 190.0, 145.0, 81.0, 22.0 ] } },
      { "box": { "id": "snap-out", "maxclass": "newobj", "text": "snapshot~ 20", "numinlets": 2, "numoutlets": 1, "patching_rect": [ 270.0, 270.0, 81.0, 22.0 ] } },
      { "box": { "id": "msg-a", "maxclass": "newobj", "text": "prepend a", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 40.0, 175.0, 66.0, 22.0 ] } },
      { "box": { "id": "msg-b", "maxclass": "newobj", "text": "prepend b", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 190.0, 175.0, 66.0, 22.0 ] } },
      { "box": { "id": "msg-out", "maxclass": "newobj", "text": "prepend output", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 270.0, 305.0, 90.0, 22.0 ] } },
      { "box": { "id": "snap-rawa", "maxclass": "newobj", "text": "snapshot~ 20", "numinlets": 2, "numoutlets": 1, "patching_rect": [ 120.0, 250.0, 81.0, 22.0 ] } },
      { "box": { "id": "snap-rawb", "maxclass": "newobj", "text": "snapshot~ 20", "numinlets": 2, "numoutlets": 1, "patching_rect": [ 340.0, 250.0, 81.0, 22.0 ] } },
      { "box": { "id": "msg-rawa", "maxclass": "newobj", "text": "prepend rawa", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 120.0, 280.0, 80.0, 22.0 ] } },
      { "box": { "id": "msg-rawb", "maxclass": "newobj", "text": "prepend rawb", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 340.0, 280.0, 80.0, 22.0 ] } },
      { "box": { "id": "load", "maxclass": "newobj", "text": "loadbang", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 600.0, 35.0, 58.0, 22.0 ] } },
      { "box": { "id": "fit", "maxclass": "newobj", "text": "v8 attractorFit.js ui", "numinlets": 1, "numoutlets": 1, "patching_rect": [ 570.0, 75.0, 130.0, 22.0 ] } },
      { "box": { "id": "auto", "maxclass": "newobj", "text": "autopattr", "varname": "uMotionLogic", "numinlets": 1, "numoutlets": 4, "patching_rect": [ 600.0, 330.0, 56.0, 22.0 ], "restore": { "combineSelect": [ 0.0 ] } } }
    ],
    "lines": [
      { "patchline": { "source": [ "in-a", 0 ], "destination": [ "dir-a", 0 ] } },
      { "patchline": { "source": [ "in-b", 0 ], "destination": [ "dir-b", 0 ] } },
      { "patchline": { "source": [ "in-op", 0 ], "destination": [ "scale", 0 ] } },
      { "patchline": { "source": [ "scale", 0 ], "destination": [ "op", 0 ] } },
      { "patchline": { "source": [ "dir-a", 0 ], "destination": [ "morph", 0 ], "order": 1 } },
      { "patchline": { "source": [ "dir-a", 0 ], "destination": [ "snap-a", 0 ], "order": 0 } },
      { "patchline": { "source": [ "dir-b", 0 ], "destination": [ "morph", 1 ], "order": 1 } },
      { "patchline": { "source": [ "dir-b", 0 ], "destination": [ "snap-b", 0 ], "order": 0 } },
      { "patchline": { "source": [ "morph", 0 ], "destination": [ "gate", 0 ] } },
      { "patchline": { "source": [ "gate", 0 ], "destination": [ "edge", 0 ], "order": 1 } },
      { "patchline": { "source": [ "gate", 0 ], "destination": [ "snap-out", 0 ], "order": 0 } },
      { "patchline": { "source": [ "edge", 0 ], "destination": [ "rise", 0 ] } },
      { "patchline": { "source": [ "edge", 1 ], "destination": [ "fall", 0 ] } },
      { "patchline": { "source": [ "op", 0 ], "destination": [ "op-gen", 0 ], "order": 1 } },
      { "patchline": { "source": [ "op", 0 ], "destination": [ "op-ui", 0 ], "order": 0 } },
      { "patchline": { "source": [ "op-gen", 0 ], "destination": [ "morph", 0 ] } },
      { "patchline": { "source": [ "op-ui", 0 ], "destination": [ "ui", 0 ] } },
      { "patchline": { "source": [ "ui", 0 ], "destination": [ "op", 0 ] } },
      { "patchline": { "source": [ "snap-a", 0 ], "destination": [ "msg-a", 0 ] } },
      { "patchline": { "source": [ "snap-b", 0 ], "destination": [ "msg-b", 0 ] } },
      { "patchline": { "source": [ "snap-out", 0 ], "destination": [ "msg-out", 0 ] } },
      { "patchline": { "source": [ "msg-a", 0 ], "destination": [ "ui", 0 ] } },
      { "patchline": { "source": [ "in-a", 0 ], "destination": [ "snap-rawa", 0 ] } },
      { "patchline": { "source": [ "in-b", 0 ], "destination": [ "snap-rawb", 0 ] } },
      { "patchline": { "source": [ "snap-rawa", 0 ], "destination": [ "msg-rawa", 0 ] } },
      { "patchline": { "source": [ "snap-rawb", 0 ], "destination": [ "msg-rawb", 0 ] } },
      { "patchline": { "source": [ "msg-rawa", 0 ], "destination": [ "ui", 0 ] } },
      { "patchline": { "source": [ "msg-rawb", 0 ], "destination": [ "ui", 0 ] } },
      { "patchline": { "source": [ "msg-b", 0 ], "destination": [ "ui", 0 ] } },
      { "patchline": { "source": [ "msg-out", 0 ], "destination": [ "ui", 0 ] } },
      { "patchline": { "source": [ "load", 0 ], "destination": [ "fit", 0 ], "order": 0 } },
      { "patchline": { "source": [ "load", 0 ], "destination": [ "op", 0 ], "order": 1 } }
    ],
    "dependency_cache": [
      { "name": "MotionLogic.js", "type": "TEXT", "implicit": 1 },
      { "name": "morphCombineGates.gendsp", "type": "GEN", "implicit": 1 },
      { "name": "motionLogicGate.gendsp", "type": "GEN", "implicit": 1 },
      { "name": "signChangeGates.gendsp", "type": "GEN", "implicit": 1 },
      { "name": "attractorFit.js", "type": "TEXT", "implicit": 1 }
    ],
    "autosave": 0
  }
}
