{
  "patcher": {
    "fileversion": 1,
    "appversion": { "major": 9, "minor": 1, "revision": 1, "architecture": "x64", "modernui": 1 },
    "classnamespace": "box",
    "rect": [456.0, 378.0, 700.0, 560.0],
    "openinpresentation": 1,
    "default_fontsize": 12.0,
    "default_fontface": 0,
    "default_fontname": "Arial",
    "boxes": [
      { "box": { "id": "in", "maxclass": "inlet", "comment": "Signal In", "numinlets": 0, "numoutlets": 1, "outlettype": ["signal"], "patching_rect": [55.0, 42.0, 30.0, 30.0] } },
      { "box": { "id": "ui", "maxclass": "v8ui", "filename": "ThresholdTrigger.js", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "border": 0, "patching_rect": [255.0, 42.0, 190.0, 85.0], "presentation": 1, "presentation_rect": [0.0, 0.0, 190.0, 85.0], "varname": "ui" } },
      { "box": { "id": "upper", "maxclass": "flonum", "minimum": -1.0, "maximum": 1.0, "format": 6, "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "patching_rect": [150.0, 190.0, 50.0, 22.0], "varname": "upperThresh" } },
      { "box": { "id": "lower", "maxclass": "flonum", "minimum": -1.0, "maximum": 1.0, "format": 6, "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "patching_rect": [450.0, 190.0, 50.0, 22.0], "varname": "lowerThresh" } },
      { "box": { "id": "gen", "maxclass": "newobj", "text": "gen~ thresholdCrossings", "numinlets": 1, "numoutlets": 2, "outlettype": ["signal", "signal"], "patching_rect": [255.0, 285.0, 142.0, 22.0] } },
      { "box": { "id": "high-param", "maxclass": "newobj", "text": "prepend high", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [150.0, 230.0, 80.0, 22.0] } },
      { "box": { "id": "low-param", "maxclass": "newobj", "text": "prepend low", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [450.0, 230.0, 76.0, 22.0] } },
      { "box": { "id": "upper-ui", "maxclass": "newobj", "text": "prepend upper", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [55.0, 230.0, 86.0, 22.0] } },
      { "box": { "id": "lower-ui", "maxclass": "newobj", "text": "prepend lower", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [550.0, 230.0, 86.0, 22.0] } },
      { "box": { "id": "display-snap", "maxclass": "newobj", "text": "snapshot~ 20", "numinlets": 1, "numoutlets": 1, "outlettype": ["float"], "patching_rect": [55.0, 95.0, 78.0, 22.0] } },
      { "box": { "id": "sig-ui", "maxclass": "newobj", "text": "prepend sig", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [55.0, 135.0, 72.0, 22.0] } },
      { "box": { "id": "high-snap", "maxclass": "newobj", "text": "snapshot~ 1", "numinlets": 1, "numoutlets": 1, "outlettype": ["float"], "patching_rect": [220.0, 330.0, 72.0, 22.0] } },
      { "box": { "id": "low-snap", "maxclass": "newobj", "text": "snapshot~ 1", "numinlets": 1, "numoutlets": 1, "outlettype": ["float"], "patching_rect": [410.0, 330.0, 72.0, 22.0] } },
      { "box": { "id": "drain", "maxclass": "newobj", "text": "v8 ThresholdTriggerEvents.js", "numinlets": 2, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [255.0, 375.0, 176.0, 22.0] } },
      { "box": { "id": "hi-msg", "maxclass": "message", "text": "hi", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [220.0, 420.0, 29.5, 22.0] } },
      { "box": { "id": "lo-msg", "maxclass": "message", "text": "lo", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [450.0, 420.0, 29.5, 22.0] } },
      { "box": { "id": "hi-out", "maxclass": "outlet", "comment": "Hi Trigger", "numinlets": 1, "numoutlets": 0, "patching_rect": [255.0, 485.0, 30.0, 30.0] } },
      { "box": { "id": "lo-out", "maxclass": "outlet", "comment": "Low Trigger", "numinlets": 1, "numoutlets": 0, "patching_rect": [410.0, 485.0, 30.0, 30.0] } },
      { "box": { "id": "load", "maxclass": "newobj", "text": "loadbang", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [560.0, 42.0, 58.0, 22.0] } },
      { "box": { "id": "fit", "maxclass": "newobj", "text": "v8 attractorFit.js ui", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [525.0, 125.0, 130.0, 22.0] } },
      { "box": { "id": "auto", "maxclass": "newobj", "text": "autopattr", "numinlets": 1, "numoutlets": 4, "outlettype": ["", "", "", ""], "patching_rect": [560.0, 82.0, 56.0, 22.0], "restore": { "lowerThresh": [0.0], "upperThresh": [0.0] }, "varname": "u550013009" } }
    ],
    "lines": [
      { "patchline": { "source": ["in", 0], "destination": ["gen", 0], "order": 1 } },
      { "patchline": { "source": ["in", 0], "destination": ["display-snap", 0], "order": 0 } },
      { "patchline": { "source": ["display-snap", 0], "destination": ["sig-ui", 0] } },
      { "patchline": { "source": ["sig-ui", 0], "destination": ["ui", 0] } },
      { "patchline": { "source": ["ui", 0], "destination": ["upper", 0] } },
      { "patchline": { "source": ["ui", 1], "destination": ["lower", 0] } },
      { "patchline": { "source": ["upper", 0], "destination": ["high-param", 0], "order": 1 } },
      { "patchline": { "source": ["upper", 0], "destination": ["upper-ui", 0], "order": 0 } },
      { "patchline": { "source": ["lower", 0], "destination": ["low-param", 0], "order": 1 } },
      { "patchline": { "source": ["lower", 0], "destination": ["lower-ui", 0], "order": 0 } },
      { "patchline": { "source": ["high-param", 0], "destination": ["gen", 0] } },
      { "patchline": { "source": ["low-param", 0], "destination": ["gen", 0] } },
      { "patchline": { "source": ["upper-ui", 0], "destination": ["ui", 0] } },
      { "patchline": { "source": ["lower-ui", 0], "destination": ["ui", 0] } },
      { "patchline": { "source": ["gen", 0], "destination": ["high-snap", 0] } },
      { "patchline": { "source": ["gen", 1], "destination": ["low-snap", 0] } },
      { "patchline": { "source": ["high-snap", 0], "destination": ["drain", 0] } },
      { "patchline": { "source": ["low-snap", 0], "destination": ["drain", 1] } },
      { "patchline": { "source": ["drain", 0], "destination": ["hi-out", 0], "order": 1 } },
      { "patchline": { "source": ["drain", 0], "destination": ["hi-msg", 0], "order": 0 } },
      { "patchline": { "source": ["drain", 1], "destination": ["lo-out", 0], "order": 1 } },
      { "patchline": { "source": ["drain", 1], "destination": ["lo-msg", 0], "order": 0 } },
      { "patchline": { "source": ["hi-msg", 0], "destination": ["ui", 0] } },
      { "patchline": { "source": ["lo-msg", 0], "destination": ["ui", 0] } },
      { "patchline": { "source": ["load", 0], "destination": ["upper", 0], "order": 1 } },
      { "patchline": { "source": ["load", 0], "destination": ["lower", 0], "order": 0 } },
      { "patchline": { "source": ["load", 0], "destination": ["fit", 0], "order": 2 } }
    ],
    "dependency_cache": [],
    "autosave": 0
  }
}
